// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhd4A5fcBuh72kDUYtUKa0AVVfy-leUjw',
    appId: '1:886807399906:web:9bb81d7873c35783183dbb',
    messagingSenderId: '886807399906',
    projectId: 'quanlyxe-f18f4',
    authDomain: 'quanlyxe-f18f4.firebaseapp.com',
    storageBucket: 'quanlyxe-f18f4.firebasestorage.app',
    databaseURL: 'https://quanlyxe-f18f4.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeu5pUkeuGWIJVZcOvmFxf7scuQK9Iz_A',
    appId: '1:886807399906:android:fce77983c8e6f915183dbb',
    messagingSenderId: '886807399906',
    projectId: 'quanlyxe-f18f4',
    storageBucket: 'quanlyxe-f18f4.firebasestorage.app',
    databaseURL: 'https://quanlyxe-f18f4.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0aHbIjeUMEl8BO6OGN80JgtxNzVYITs',
    appId: '1:886807399906:ios:850797e101665d36183dbb',
    messagingSenderId: '886807399906',
    projectId: 'quanlyxe-f18f4',
    storageBucket: 'quanlyxe-f18f4.firebasestorage.app',
    databaseURL: 'https://quanlyxe-f18f4.firebaseio.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0aHbIjeUMEl8BO6OGN80JgtxNzVYITs',
    appId: '1:886807399906:ios:850797e101665d36183dbb',
    messagingSenderId: '886807399906',
    projectId: 'quanlyxe-f18f4',
    storageBucket: 'quanlyxe-f18f4.firebasestorage.app',
    databaseURL: 'https://quanlyxe-f18f4.firebaseio.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhd4A5fcBuh72kDUYtUKa0AVVfy-leUjw',
    appId: '1:886807399906:web:aa09726ea8d478ec183dbb',
    messagingSenderId: '886807399906',
    projectId: 'quanlyxe-f18f4',
    authDomain: 'quanlyxe-f18f4.firebaseapp.com',
    storageBucket: 'quanlyxe-f18f4.firebasestorage.app',
    databaseURL: 'https://quanlyxe-f18f4.firebaseio.com',
  );
}
