/// Sample parking locations with GPS coordinates for Vietnam (Hà Nội area)
class SampleParkingLocations {
  static const List<Map<String, dynamic>> locations = [
    {
      'id': 'loc_1',
      'name': 'Bãi xe Hà Nội - Hoàn Kiếm',
      'address': '42 Hàng Trống, Hoàn Kiếm, Hà Nội',
      'lat': 21.029069,
      'lng': 105.852261,
      'totalSpots': 50,
      'pricePerHour': 25000,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Hoàn+Kiếm',
      'description': 'Bãi xe trung tâm, gần các điểm du lịch',
    },
    {
      'id': 'loc_2',
      'name': 'Bãi xe Tây Hồ',
      'address': 'Đường Thanh Niên, Tây Hồ, Hà Nội',
      'lat': 21.089163,
      'lng': 105.823480,
      'totalSpots': 75,
      'pricePerHour': 20000,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Tây+Hồ',
      'description': 'Bãi xe rộng rãi, giá hợp lý',
    },
    {
      'id': 'loc_3',
      'name': 'Bãi xe Cầu Giấy',
      'address': 'Phố Duy Tân, Cầu Giấy, Hà Nội',
      'lat': 21.011389,
      'lng': 105.791667,
      'totalSpots': 100,
      'pricePerHour': 30000,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Cầu+Giấy',
      'description': 'Bãi xe VIP, có quầy bảo dưỡng',
    },
    {
      'id': 'loc_4',
      'name': 'Bãi xe Thanh Xuân',
      'address': 'Đường Thanh Xuân, Thanh Xuân, Hà Nội',
      'lat': 21.007722,
      'lng': 105.868056,
      'totalSpots': 60,
      'pricePerHour': 22000,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Thanh+Xuân',
      'description': 'Bãi xe sạch sẽ, an toàn',
    },
    {
      'id': 'loc_5',
      'name': 'Bãi xe Hai Bà Trưng',
      'address': 'Đường Bà Triệu, Hai Bà Trưng, Hà Nội',
      'lat': 21.020833,
      'lng': 105.880278,
      'totalSpots': 80,
      'pricePerHour': 28000,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Hai+Bà+Trưng',
      'description': 'Bãi xe gần trung tâm, dịch vụ 24/7',
    },
  ];
}
